# Commands to start on workspace startup
image: eyck/gitpod-riscv-tools:latest
        #  file: .gitpod.Dockerfile
tasks:
  - init: |
       export CONAN_USER_HOME=/workspace/conan
       python3 -m pip install --upgrade pip
       python3 -m pip install conan
       conan profile new default --detect --force
       conan profile update settings.compiler.libcxx=libstdc++11 default
       mkdir -p build
       cd build
       cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
       make -j
       cd ..

vscode:
  extensions:
    - ms-vscode.cmake-tools
    - ms-python.python