# Commands to start on workspace startup
image: eyck/gitpod-riscv-tools
tasks:
  - init: | 
       python3 -m pip install --upgrade pip
       python3 -m pip install conan
    command: |
       conan profile new default --detect --force
       conan profile update settings.compiler.libcxx=libstdc++11 default
       mkdir -p build
       cd build
       cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
       make -j
